import { Tenant, TenantSummary } from "@/types/tenant";

export const mockTenants: Tenant[] = [
  {
    id: "tn_acme_corp_001",
    slug: "acme-corp",
    name: "Acme Corporation",
    status: "active",
    region: "eu-central-1",
    dataResidency: "EU",
    contactEmail: "admin@acmecorp.com",
    createdAt: "2024-01-15T10:30:00Z",
    plan: "Enterprise",
    verifications24h: 3420,
    verifications30d: 98450,
    successRate: 94.2,
    activeUsers: 12,
    apiKeys: 4,
    webhooks: ["https://api.acmecorp.com/webhooks/idv"],
    features: {
      ocrEnabled: true,
      faceMatchEnabled: true,
      livenessEnabled: true,
      amlEnabled: true,
    },
    quotas: {
      monthlyVerifications: 100000,
      used: 98450,
    },
  },
  {
    id: "tn_fintech_pro_002",
    slug: "fintech-pro",
    name: "FinTech Pro Ltd",
    status: "active",
    region: "us-east-1",
    dataResidency: "US",
    contactEmail: "ops@fintechpro.io",
    createdAt: "2024-02-20T14:15:00Z",
    plan: "Professional",
    verifications24h: 1820,
    verifications30d: 52300,
    successRate: 96.8,
    activeUsers: 8,
    apiKeys: 3,
    webhooks: ["https://webhooks.fintechpro.io/idv", "https://backup.fintechpro.io/hooks"],
    features: {
      ocrEnabled: true,
      faceMatchEnabled: true,
      livenessEnabled: true,
      amlEnabled: false,
    },
    quotas: {
      monthlyVerifications: 75000,
      used: 52300,
    },
  },
  {
    id: "tn_startup_inc_003",
    slug: "startup-inc",
    name: "Startup Inc",
    status: "trial",
    region: "us-west-2",
    dataResidency: "US",
    contactEmail: "dev@startup.io",
    createdAt: "2024-10-05T09:00:00Z",
    plan: "Trial",
    verifications24h: 145,
    verifications30d: 2840,
    successRate: 89.5,
    activeUsers: 3,
    apiKeys: 1,
    webhooks: [],
    features: {
      ocrEnabled: true,
      faceMatchEnabled: true,
      livenessEnabled: false,
      amlEnabled: false,
    },
    quotas: {
      monthlyVerifications: 5000,
      used: 2840,
    },
  },
  {
    id: "tn_global_bank_004",
    slug: "global-bank",
    name: "Global Bank Solutions",
    status: "active",
    region: "eu-central-1",
    dataResidency: "EU",
    contactEmail: "compliance@globalbank.com",
    createdAt: "2023-11-10T08:45:00Z",
    plan: "Enterprise Plus",
    verifications24h: 8920,
    verifications30d: 287600,
    successRate: 97.3,
    activeUsers: 45,
    apiKeys: 12,
    webhooks: ["https://prod.globalbank.com/idv/webhook", "https://dr.globalbank.com/idv/webhook"],
    features: {
      ocrEnabled: true,
      faceMatchEnabled: true,
      livenessEnabled: true,
      amlEnabled: true,
    },
    quotas: {
      monthlyVerifications: 500000,
      used: 287600,
    },
  },
  {
    id: "tn_crypto_ex_005",
    slug: "crypto-exchange",
    name: "CryptoExchange",
    status: "suspended",
    region: "us-east-1",
    dataResidency: "US",
    contactEmail: "security@cryptoex.com",
    createdAt: "2024-03-12T11:20:00Z",
    plan: "Professional",
    verifications24h: 0,
    verifications30d: 18200,
    successRate: 82.1,
    activeUsers: 0,
    apiKeys: 2,
    webhooks: ["https://api.cryptoex.com/verify"],
    features: {
      ocrEnabled: true,
      faceMatchEnabled: true,
      livenessEnabled: true,
      amlEnabled: true,
    },
    quotas: {
      monthlyVerifications: 50000,
      used: 18200,
    },
    riskFlags: ["Suspended for AML review", "High fraud rate detected"],
  },
  {
    id: "tn_ecom_asia_006",
    slug: "ecom-asia",
    name: "E-Commerce Asia",
    status: "active",
    region: "ap-southeast-1",
    dataResidency: "APAC",
    contactEmail: "tech@ecomasia.com",
    createdAt: "2024-06-18T07:30:00Z",
    plan: "Growth",
    verifications24h: 2340,
    verifications30d: 68900,
    successRate: 91.7,
    activeUsers: 15,
    apiKeys: 5,
    webhooks: ["https://api.ecomasia.com/idv/webhook"],
    features: {
      ocrEnabled: true,
      faceMatchEnabled: true,
      livenessEnabled: false,
      amlEnabled: false,
    },
    quotas: {
      monthlyVerifications: 100000,
      used: 68900,
    },
  },
  {
    id: "tn_insurance_co_007",
    slug: "insurance-co",
    name: "InsuranceCo International",
    status: "active",
    region: "eu-central-1",
    dataResidency: "EU",
    contactEmail: "it@insuranceco.eu",
    createdAt: "2024-04-22T13:00:00Z",
    plan: "Enterprise",
    verifications24h: 1560,
    verifications30d: 43200,
    successRate: 95.4,
    activeUsers: 22,
    apiKeys: 6,
    webhooks: ["https://hooks.insuranceco.eu/idv"],
    features: {
      ocrEnabled: true,
      faceMatchEnabled: true,
      livenessEnabled: true,
      amlEnabled: true,
    },
    quotas: {
      monthlyVerifications: 75000,
      used: 43200,
    },
  },
  {
    id: "tn_travel_app_008",
    slug: "travel-app",
    name: "TravelApp Global",
    status: "inactive",
    region: "us-west-2",
    dataResidency: "US",
    contactEmail: "support@travelapp.com",
    createdAt: "2023-08-30T16:45:00Z",
    plan: "Growth",
    verifications24h: 0,
    verifications30d: 120,
    successRate: 88.2,
    activeUsers: 1,
    apiKeys: 1,
    webhooks: [],
    features: {
      ocrEnabled: true,
      faceMatchEnabled: false,
      livenessEnabled: false,
      amlEnabled: false,
    },
    quotas: {
      monthlyVerifications: 25000,
      used: 120,
    },
    riskFlags: ["Inactive for 60+ days"],
  },
];

export const getTenantSummaries = (): TenantSummary[] => {
  return mockTenants.map((tenant) => ({
    id: tenant.id,
    name: tenant.name,
    status: tenant.status,
    region: tenant.region,
    verifications24h: tenant.verifications24h,
    successRate: tenant.successRate,
    plan: tenant.plan,
    riskFlags: tenant.riskFlags,
  }));
};

export const getTenantById = (id: string): Tenant | undefined => {
  return mockTenants.find((tenant) => tenant.id === id);
};
